# Generated by Django 5.2.5 on 2025-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="photo1",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="photo4",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="photo5",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
