# Generated by Django 5.2.5 on 2025-08-26 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_recipe_photo1_recipe_photo2_recipe_photo3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_info",
            old_name="name",
            new_name="username",
        ),
    ]
