# Generated by Django 5.2.5 on 2025-08-26 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_name_user_info_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_info",
        ),
    ]
