# Generated by Django 5.2.5 on 2025-08-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_delete_user_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
